usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /


portada:
    resource: "@PortadaBundle/Resources/config/routing.yml"
    prefix:   /

grupo:
    resource: "@GrupoBundle/Resources/config/routing.yml"
    prefix:   /

nivel:
    resource: "@NivelBundle/Resources/config/routing.yml"
    prefix:   /

noticias:
    resource: "@NoticiasBundle/Resources/config/routing.yml"
    prefix:   /admin



admin_login:
    pattern: /admin/login
    defaults: { _controller: BackendBundle:Security:login }
 
admin_login_check:
    pattern: /admin/login_check
 
admin_logout:
    pattern: /admin/logout

