imagen:
    resource: "@ImagenBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

eventos:
    resource: "@EventosBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /


portada:
    resource: "@PortadaBundle/Resources/config/routing.yml"
    prefix:   /

grupo:
    resource: "@GrupoBundle/Resources/config/routing.yml"
    prefix:   /

noticias:
    resource: "@NoticiasBundle/Resources/config/routing.yml"
    prefix:   /

admin_login:
    path:     /admin/login
    defaults: { _controller: BackendBundle:Security:login }

admin_login_check:
    path: /admin/login_check

admin_logout:
    pattern: /admin/logout

