security:
    firewalls:
        # Firewall global utilizado en la parte pública o frontend
        backend:
            pattern:   ^/admin
            provider: administradores
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check

            logout:
                path: admin_logout
                target: admin_login

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_USER }
        - { path: ^/admin/*, roles: ROLE_ADMIN }


    providers:
        administradores:
            entity: { class: Alzheimer\UsuarioBundle\Entity\Usuario, property: username }

    encoders:
        Alzheimer\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]